# Generated by Django 5.0.2 on 2024-02-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlow',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
